name: discord_rich_presence
description: Discord Rich Presence library for Dart.
repository: https://github.com/NotZoeyDev/discord_rich_presence
version: 1.1.1

environment:
  sdk: ^3.5.3

dependencies:
  uuid: ^4.5.1
  typed_data: ^1.4.0
  buffer: ^1.2.3
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
